# Terraform Docs Configuration
formatter: "markdown table"

header-from: "README.md"
footer-from: ""

sections:
  hide:
  - header
  - footer
  - requirements
  - providers
  - modules
  - resources
  show:
  - inputs
  - outputs

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
